/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var define_pb = require('./define_pb.js');
goog.exportSymbol('proto.MatchStock', null, global);
goog.exportSymbol('proto.MatchStockResp', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MatchStockResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MatchStockResp.repeatedFields_, null);
};
goog.inherits(proto.MatchStockResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MatchStockResp.displayName = 'proto.MatchStockResp';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MatchStockResp.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MatchStockResp.prototype.toObject = function(opt_includeInstance) {
  return proto.MatchStockResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MatchStockResp} msg The msg instance to transform.
 * @return {!Object}
 */
proto.MatchStockResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorcode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stocklistList: jspb.Message.toObjectList(msg.getStocklistList(),
    proto.MatchStock.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MatchStockResp}
 */
proto.MatchStockResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MatchStockResp;
  return proto.MatchStockResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MatchStockResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MatchStockResp}
 */
proto.MatchStockResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 2:
      var value = new proto.MatchStock;
      reader.readMessage(value,proto.MatchStock.deserializeBinaryFromReader);
      msg.addStocklist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MatchStockResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MatchStockResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MatchStockResp} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.MatchStockResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStocklistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.MatchStock.serializeBinaryToWriter
    );
  }
};


/**
 * optional ErrorCode errorCode = 1;
 * @return {!proto.ErrorCode}
 */
proto.MatchStockResp.prototype.getErrorcode = function() {
  return /** @type {!proto.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.ErrorCode} value */
proto.MatchStockResp.prototype.setErrorcode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated MatchStock stockList = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.MatchStock>}
 */
proto.MatchStockResp.prototype.getStocklistList = function() {
  return /** @type{!Array.<!proto.MatchStock>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MatchStock, 2));
};


/** @param {!Array.<!proto.MatchStock>} value */
proto.MatchStockResp.prototype.setStocklistList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.MatchStock=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MatchStock}
 */
proto.MatchStockResp.prototype.addStocklist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.MatchStock, opt_index);
};


proto.MatchStockResp.prototype.clearStocklistList = function() {
  this.setStocklistList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MatchStock = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MatchStock, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MatchStock.displayName = 'proto.MatchStock';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MatchStock.prototype.toObject = function(opt_includeInstance) {
  return proto.MatchStock.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MatchStock} msg The msg instance to transform.
 * @return {!Object}
 */
proto.MatchStock.toObject = function(includeInstance, msg) {
  var f, obj = {
    stocklabel: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stockname: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MatchStock}
 */
proto.MatchStock.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MatchStock;
  return proto.MatchStock.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MatchStock} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MatchStock}
 */
proto.MatchStock.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStocklabel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStockname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MatchStock.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MatchStock.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MatchStock} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.MatchStock.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStocklabel();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStockname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string stockLabel = 1;
 * @return {string}
 */
proto.MatchStock.prototype.getStocklabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.MatchStock.prototype.setStocklabel = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string stockName = 2;
 * @return {string}
 */
proto.MatchStock.prototype.getStockname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.MatchStock.prototype.setStockname = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto);
